//----------------------------------------------------------------------------------------------------------------------
/*!
   \file
   \brief       Application specific openSYDE initialization (Source file with implementation)

   This file was generated by openSYDE osy_syde_coder_c.exe V1.13r0, MD5-Checksum: 3FF0BA0464B443BC0A1289AE9DC7DCC2.
*/
//----------------------------------------------------------------------------------------------------------------------

/* -- Includes ------------------------------------------------------------------------------------------------------ */
#include <stddef.h> //for NULL
#include "stwtypes.h"
#include "osy_init.h"
#include "osy_dpa_data_pool.h"

/* -- Defines ------------------------------------------------------------------------------------------------------- */

/* -- Types --------------------------------------------------------------------------------------------------------- */

/* -- Global Variables ---------------------------------------------------------------------------------------------- */

/* -- Module Global Variables --------------------------------------------------------------------------------------- */

/* -- Module Global Function Prototypes ----------------------------------------------------------------------------- */

/* -- Implementation ------------------------------------------------------------------------------------------------ */

//----------------------------------------------------------------------------------------------------------------------
/*! \brief   Set up and provide openSYDE protocol driver configuration

   Sets up:
   * CAN channel configuration
   * Ethernet channel configuration
   * Connection buffer definition
   * Main initialization structure

   \return
   pointer to configuration structure (statically available; can be used for the DPD initialization function)
*/
//----------------------------------------------------------------------------------------------------------------------
const T_osy_dpd_data * osy_dpd_get_init_config(void)
{
   OSY_DPD_CAN_CHANNEL(ht_CanInitConfiguration0, OSY_INIT_DPD_BUS_NUMBER_CAN_CHANNEL_0,
                       OSY_INIT_DPD_NUMBER_OF_PARALLEL_CONNECTIONS, OSY_INIT_DPD_NUMBER_OF_PARALLEL_CONNECTIONS,
                       OSY_INIT_DPD_BUF_SIZE_INSTANCE,
                       OSY_INIT_DPD_CAN_FIFO_SIZE_TX, OSY_INIT_DPD_CAN_ROUTING_FIFO_SIZE_RX)
   OSY_DPD_CAN_CHANNEL(ht_CanInitConfiguration1, OSY_INIT_DPD_BUS_NUMBER_CAN_CHANNEL_1,
                       OSY_INIT_DPD_NUMBER_OF_PARALLEL_CONNECTIONS, OSY_INIT_DPD_NUMBER_OF_PARALLEL_CONNECTIONS,
                       OSY_INIT_DPD_BUF_SIZE_INSTANCE,
                       OSY_INIT_DPD_CAN_FIFO_SIZE_TX, OSY_INIT_DPD_CAN_ROUTING_FIFO_SIZE_RX)

   static const T_osy_udc_global_cantp_init_configuration * const
      hapt_CanInitConfigurations[OSY_INIT_DPD_NUMBER_OF_CAN_CHANNELS] =
   {
      &ht_CanInitConfiguration0,
      &ht_CanInitConfiguration1
   };


   OSY_DPD_CONNECTION_INSTANCE_INIT(ht_DpdConnectionInstance0, 0U, OSY_INIT_DPD_MAX_NUM_CYCLIC_TRANSMISSIONS)

   static T_osy_dpd_connection_instance * const hapt_DpdConnections[OSY_INIT_DPD_NUMBER_OF_PARALLEL_CONNECTIONS] =
   {
      &ht_DpdConnectionInstance0
   };

   OSY_DPD_GLOBAL_DATA_INIT(ht_DpdDataInstance,
                            OSY_INIT_DPD_NUMBER_OF_CAN_CHANNELS,
                            OSY_INIT_DPD_NUMBER_OF_ETHERNET_CHANNELS,
                            OSY_INIT_DPD_NUMBER_OF_PARALLEL_CONNECTIONS,
                            &hapt_DpdConnections[0],
                            &hapt_CanInitConfigurations[0],
                            NULL)

   return &ht_DpdDataInstance;
}

//----------------------------------------------------------------------------------------------------------------------
/*! \brief   Set up and provide openSYDE Datapool handler configuration

   Sets up:
   * initialization structure listing all Datapools in correct sequence

   \return
   pointer to initialization structure (statically available; can be used for the DPH initialization function)
   NULL: no Datapools defined
*/
//----------------------------------------------------------------------------------------------------------------------
const T_osy_dpa_data_pool * const * osy_dph_get_init_config(void)
{
   static const T_osy_dpa_data_pool * const hapt_Datapools[OSY_INIT_DPH_NUM_DATA_POOLS] =
   {
      &gt_Diagnostics_DataPool
   };

   return &hapt_Datapools[0];
}

//----------------------------------------------------------------------------------------------------------------------
/*! \brief   Get number of defined openSYDE Datapools

   \return
   number of openSYDE Datapools
*/
//----------------------------------------------------------------------------------------------------------------------
uint8 osy_dph_get_num_data_pools(void)
{
   return OSY_INIT_DPH_NUM_DATA_POOLS;
}
