//----------------------------------------------------------------------------------------------------------------------
/*!
   \file
   \brief       Application specific openSYDE initialization (Header file with interface)

   This file was generated by openSYDE osy_syde_coder_c.exe V1.13r0, MD5-Checksum: 3FF0BA0464B443BC0A1289AE9DC7DCC2.
*/
//----------------------------------------------------------------------------------------------------------------------
#ifndef OSY_INITH
#define OSY_INITH

/* -- Includes ------------------------------------------------------------------------------------------------------ */
#include "stwtypes.h"
#include "osy_dpd_driver.h"
#include "osy_dpa_data_pool.h"
//Header files exporting application specific Datapools:
#include "diagnostics_data_pool.h"
//Header files exporting comm stack configuration and status:

#ifdef __cplusplus
extern "C" {
#endif

/* -- Defines ------------------------------------------------------------------------------------------------------- */
#define OSY_INIT_DPD_BUS_NUMBER_CAN_CHANNEL_0       0U
#define OSY_INIT_DPD_BUS_NUMBER_CAN_CHANNEL_1       1U
#define OSY_INIT_DPD_NUMBER_OF_CAN_CHANNELS         2U
#define OSY_INIT_DPD_NUMBER_OF_ETHERNET_CHANNELS    0U

#define OSY_INIT_DPD_NUMBER_OF_PARALLEL_CONNECTIONS 1U
#define OSY_INIT_DPD_CAN_FIFO_SIZE_TX               585U
#define OSY_INIT_DPD_CAN_ROUTING_FIFO_SIZE_RX       585U
#define OSY_INIT_DPD_BUF_SIZE_INSTANCE              55U
#define OSY_INIT_DPD_MAX_NUM_CYCLIC_TRANSMISSIONS   64U

#define OSY_INIT_DPH_NUM_DATA_POOLS                 1U

#define OSY_INIT_COM_NUM_PROTOCOL_CONFIGURATIONS    0U

/* -- Types --------------------------------------------------------------------------------------------------------- */

/* -- Global Variables ---------------------------------------------------------------------------------------------- */

/* -- Function Prototypes ------------------------------------------------------------------------------------------- */
extern const T_osy_dpd_data * osy_dpd_get_init_config(void);
extern const T_osy_dpa_data_pool * const * osy_dph_get_init_config(void);
extern uint8 osy_dph_get_num_data_pools(void);

/* -- Implementation ------------------------------------------------------------------------------------------------ */

#ifdef __cplusplus
} /* end of extern "C" */
#endif

#endif
